version: "3"

services:
    kopiya:
        image: kopiya:latest
        container_name: kopiya
        depends_on:
            - "redis"
            - "postgres"
        ports:
            - 3000:3000
        env_file: .env
        volumes:
            - ./config.toml:/usr/src/app/config.toml

    redis:
        image: redis
        container_name: kopiya-redis
        expose:
            - 6379

    postgres:
        image: postgres
        container_name: kopiya-postgres
        expose:
            - 5432
        env_file: .env
